# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-Velleman-K8055
version:      0.02
version_from: lib\Device\Velleman\K8055.pm
installdirs:  site
requires:
    Test::More:                    0
    Win32::API:                    0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
